//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataUpdaterGameQuestions {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class DatabasesSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DatabasesSettings defaultInstance = ((DatabasesSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DatabasesSettings())));
        
        public static DatabasesSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server = 127.0.0.1;Uid=root;Password=P@ssw0rd;Database=wwtbam;Character Set=utf8;" +
            "")]
        public string showtimeDBconnectionSQL {
            get {
                return ((string)(this["showtimeDBconnectionSQL"]));
            }
            set {
                this["showtimeDBconnectionSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gamequestions")]
        public string QuestionDB_setTable1 {
            get {
                return ((string)(this["QuestionDB_setTable1"]));
            }
            set {
                this["QuestionDB_setTable1"] = value;
            }
        }
    }
}
