//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionEditAndPreset {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class AdvancedGameConfigSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AdvancedGameConfigSettings defaultInstance = ((AdvancedGameConfigSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AdvancedGameConfigSettings())));
        
        public static AdvancedGameConfigSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MainGame")]
        public string GamePlay1_Name {
            get {
                return ((string)(this["GamePlay1_Name"]));
            }
            set {
                this["GamePlay1_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GamePlay1_QAChoices {
            get {
                return ((int)(this["GamePlay1_QAChoices"]));
            }
            set {
                this["GamePlay1_QAChoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int GamePlay1_TotalStackQ {
            get {
                return ((int)(this["GamePlay1_TotalStackQ"]));
            }
            set {
                this["GamePlay1_TotalStackQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FastestFingerFirst")]
        public string QualificationGame1_Name {
            get {
                return ((string)(this["QualificationGame1_Name"]));
            }
            set {
                this["QualificationGame1_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int QualificationGame1_QAChoices {
            get {
                return ((int)(this["QualificationGame1_QAChoices"]));
            }
            set {
                this["QualificationGame1_QAChoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int QualificationGame1_TotalStackQ {
            get {
                return ((int)(this["QualificationGame1_TotalStackQ"]));
            }
            set {
                this["QualificationGame1_TotalStackQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QualificationGame1_RightOrderYN {
            get {
                return ((bool)(this["QualificationGame1_RightOrderYN"]));
            }
            set {
                this["QualificationGame1_RightOrderYN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StackBuild_RepeatCategoriesYN {
            get {
                return ((bool)(this["StackBuild_RepeatCategoriesYN"]));
            }
            set {
                this["StackBuild_RepeatCategoriesYN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int StackBuild_UnusedUsedBothQ {
            get {
                return ((int)(this["StackBuild_UnusedUsedBothQ"]));
            }
            set {
                this["StackBuild_UnusedUsedBothQ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StackBuild_UseOnlyCatIDs {
            get {
                return ((string)(this["StackBuild_UseOnlyCatIDs"]));
            }
            set {
                this["StackBuild_UseOnlyCatIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StackBuild_ExcludeCatIDs {
            get {
                return ((string)(this["StackBuild_ExcludeCatIDs"]));
            }
            set {
                this["StackBuild_ExcludeCatIDs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MapLevelDifficult_DefaultMaping {
            get {
                return ((string)(this["MapLevelDifficult_DefaultMaping"]));
            }
            set {
                this["MapLevelDifficult_DefaultMaping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetMoneyTree_DefaultTree {
            get {
                return ((string)(this["SetMoneyTree_DefaultTree"]));
            }
            set {
                this["SetMoneyTree_DefaultTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string UsageSelectionQuery {
            get {
                return ((string)(this["UsageSelectionQuery"]));
            }
            set {
                this["UsageSelectionQuery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TopBottomSelectionQuery {
            get {
                return ((string)(this["TopBottomSelectionQuery"]));
            }
            set {
                this["TopBottomSelectionQuery"] = value;
            }
        }
    }
}
