//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionEditAndPreset {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class DatabasesSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DatabasesSettings defaultInstance = ((DatabasesSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DatabasesSettings())));
        
        public static DatabasesSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string QuestionDB_defaultHost {
            get {
                return ((string)(this["QuestionDB_defaultHost"]));
            }
            set {
                this["QuestionDB_defaultHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string QuestionDB_defaultUser {
            get {
                return ((string)(this["QuestionDB_defaultUser"]));
            }
            set {
                this["QuestionDB_defaultUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string QuestionDB_defaultPassword {
            get {
                return ((string)(this["QuestionDB_defaultPassword"]));
            }
            set {
                this["QuestionDB_defaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wwtbam")]
        public string QuestionDB_defaultDatabase {
            get {
                return ((string)(this["QuestionDB_defaultDatabase"]));
            }
            set {
                this["QuestionDB_defaultDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gamequestions")]
        public string QuestionDB_defaultTable1 {
            get {
                return ((string)(this["QuestionDB_defaultTable1"]));
            }
            set {
                this["QuestionDB_defaultTable1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ShowtimeDB_defaultHost {
            get {
                return ((string)(this["ShowtimeDB_defaultHost"]));
            }
            set {
                this["ShowtimeDB_defaultHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string ShowtimeDB_defaultUser {
            get {
                return ((string)(this["ShowtimeDB_defaultUser"]));
            }
            set {
                this["ShowtimeDB_defaultUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string ShowtimeDB_defaultPassword {
            get {
                return ((string)(this["ShowtimeDB_defaultPassword"]));
            }
            set {
                this["ShowtimeDB_defaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wwtbam")]
        public string ShowtimeDB_defaultDatabase {
            get {
                return ((string)(this["ShowtimeDB_defaultDatabase"]));
            }
            set {
                this["ShowtimeDB_defaultDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionsforcontestant")]
        public string ShowtimeDB_defaultTable1 {
            get {
                return ((string)(this["ShowtimeDB_defaultTable1"]));
            }
            set {
                this["ShowtimeDB_defaultTable1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questioncategories")]
        public string QuestionDB_defaultTable2 {
            get {
                return ((string)(this["QuestionDB_defaultTable2"]));
            }
            set {
                this["QuestionDB_defaultTable2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionsubcategories")]
        public string QuestionDB_defaultTable3 {
            get {
                return ((string)(this["QuestionDB_defaultTable3"]));
            }
            set {
                this["QuestionDB_defaultTable3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wwtbam")]
        public string QuestionDB_setDatabase {
            get {
                return ((string)(this["QuestionDB_setDatabase"]));
            }
            set {
                this["QuestionDB_setDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string QuestionDB_setHost {
            get {
                return ((string)(this["QuestionDB_setHost"]));
            }
            set {
                this["QuestionDB_setHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string QuestionDB_setPassword {
            get {
                return ((string)(this["QuestionDB_setPassword"]));
            }
            set {
                this["QuestionDB_setPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gamequestions")]
        public string QuestionDB_setTable1 {
            get {
                return ((string)(this["QuestionDB_setTable1"]));
            }
            set {
                this["QuestionDB_setTable1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questioncategories")]
        public string QuestionDB_setTable2 {
            get {
                return ((string)(this["QuestionDB_setTable2"]));
            }
            set {
                this["QuestionDB_setTable2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionsubcategories")]
        public string QuestionDB_setTable3 {
            get {
                return ((string)(this["QuestionDB_setTable3"]));
            }
            set {
                this["QuestionDB_setTable3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string QuestionDB_setUser {
            get {
                return ((string)(this["QuestionDB_setUser"]));
            }
            set {
                this["QuestionDB_setUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ShowtimeDB_setHost {
            get {
                return ((string)(this["ShowtimeDB_setHost"]));
            }
            set {
                this["ShowtimeDB_setHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P@ssw0rd")]
        public string ShowtimeDB_setPassword {
            get {
                return ((string)(this["ShowtimeDB_setPassword"]));
            }
            set {
                this["ShowtimeDB_setPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionsforcontestant")]
        public string ShowtimeDB_setTable1 {
            get {
                return ((string)(this["ShowtimeDB_setTable1"]));
            }
            set {
                this["ShowtimeDB_setTable1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string ShowtimeDB_setUser {
            get {
                return ((string)(this["ShowtimeDB_setUser"]));
            }
            set {
                this["ShowtimeDB_setUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("wwtbam")]
        public string ShowtimeDB_setDatabase {
            get {
                return ((string)(this["ShowtimeDB_setDatabase"]));
            }
            set {
                this["ShowtimeDB_setDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionstacks")]
        public string QuestionDB_setTable4 {
            get {
                return ((string)(this["QuestionDB_setTable4"]));
            }
            set {
                this["QuestionDB_setTable4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionstackitems")]
        public string QuestionDB_setTable5 {
            get {
                return ((string)(this["QuestionDB_setTable5"]));
            }
            set {
                this["QuestionDB_setTable5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionstacks")]
        public string QuestionDB_defaultTable4 {
            get {
                return ((string)(this["QuestionDB_defaultTable4"]));
            }
            set {
                this["QuestionDB_defaultTable4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("questionstackitems")]
        public string QuestionDB_defaultTable5 {
            get {
                return ((string)(this["QuestionDB_defaultTable5"]));
            }
            set {
                this["QuestionDB_defaultTable5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server = 127.0.0.1;Uid=root;Password=P@ssw0rd;Database=wwtbam;Character Set=utf8;" +
            "")]
        public string questionDBconnectionSQL {
            get {
                return ((string)(this["questionDBconnectionSQL"]));
            }
            set {
                this["questionDBconnectionSQL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Server = 127.0.0.1;Uid=root;Password=P@ssw0rd;Database=wwtbam;Character Set=utf8;" +
            "")]
        public string showtimeDBconnectionSQL {
            get {
                return ((string)(this["showtimeDBconnectionSQL"]));
            }
            set {
                this["showtimeDBconnectionSQL"] = value;
            }
        }
    }
}
