//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionEditAndPreset {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class StackSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static StackSettings defaultInstance = ((StackSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StackSettings())));
        
        public static StackSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string LiveStackID {
            get {
                return ((string)(this["LiveStackID"]));
            }
            set {
                this["LiveStackID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string LiveStackTypeChosen {
            get {
                return ((string)(this["LiveStackTypeChosen"]));
            }
            set {
                this["LiveStackTypeChosen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LiveStackNameselected {
            get {
                return ((string)(this["LiveStackNameselected"]));
            }
            set {
                this["LiveStackNameselected"] = value;
            }
        }
    }
}
